empno=int(input('Enter empno'))
name=input('Enter Name')
city=input('Enter City')

fn=input('Enter Filename.')
obj=open(fn,'a')
obj.write(str(empno)+'\n')
obj.write(name+'\n')
obj.write(city+'\n')
print('Data Saved..')
obj.close()
